package com.worklogai.app.core.designsystem.theme

import androidx.compose.ui.graphics.Color

internal val LightPrimary = Color(0xFF176B70)
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFA8EEF1)
internal val LightOnPrimaryContainer = Color(0xFF002022)
internal val LightSecondary = Color(0xFF555D7E)
internal val LightOnSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFDDE1FF)
internal val LightOnSecondaryContainer = Color(0xFF111938)
internal val LightTertiary = Color(0xFF76546D)
internal val LightOnTertiary = Color(0xFFFFFFFF)
internal val LightTertiaryContainer = Color(0xFFFFD7F1)
internal val LightOnTertiaryContainer = Color(0xFF2D1228)
internal val LightBackground = Color(0xFFF7F8F5)
internal val LightOnBackground = Color(0xFF181C1C)
internal val LightSurface = Color(0xFFF7F8F5)
internal val LightOnSurface = Color(0xFF181C1C)
internal val LightSurfaceVariant = Color(0xFFDAE5E3)
internal val LightOnSurfaceVariant = Color(0xFF3F4948)
internal val LightOutline = Color(0xFF6F7978)
internal val LightOutlineVariant = Color(0xFFBEC9C7)
internal val LightError = Color(0xFFBA1A1A)
internal val LightOnError = Color(0xFFFFFFFF)
internal val LightErrorContainer = Color(0xFFFFDAD6)
internal val LightOnErrorContainer = Color(0xFF410002)

internal val DarkPrimary = Color(0xFF89D2D6)
internal val DarkOnPrimary = Color(0xFF003739)
internal val DarkPrimaryContainer = Color(0xFF005055)
internal val DarkOnPrimaryContainer = Color(0xFFA8EEF1)
internal val DarkSecondary = Color(0xFFBCC5EB)
internal val DarkOnSecondary = Color(0xFF262E4D)
internal val DarkSecondaryContainer = Color(0xFF3D4565)
internal val DarkOnSecondaryContainer = Color(0xFFDDE1FF)
internal val DarkTertiary = Color(0xFFE5BAD7)
internal val DarkOnTertiary = Color(0xFF44263E)
internal val DarkTertiaryContainer = Color(0xFF5D3C55)
internal val DarkOnTertiaryContainer = Color(0xFFFFD7F1)
internal val DarkBackground = Color(0xFF101416)
internal val DarkOnBackground = Color(0xFFDFE3E2)
internal val DarkSurface = Color(0xFF101416)
internal val DarkOnSurface = Color(0xFFDFE3E2)
internal val DarkSurfaceVariant = Color(0xFF3F4948)
internal val DarkOnSurfaceVariant = Color(0xFFBEC9C7)
internal val DarkOutline = Color(0xFF899392)
internal val DarkOutlineVariant = Color(0xFF3F4948)
internal val DarkError = Color(0xFFFFB4AB)
internal val DarkOnError = Color(0xFF690005)
internal val DarkErrorContainer = Color(0xFF93000A)
internal val DarkOnErrorContainer = Color(0xFFFFDAD6)

val WorkLogPriorityUrgent = Color(0xFFC33B3B)
val WorkLogPriorityHigh = Color(0xFFB86413)
val WorkLogPriorityMedium = Color(0xFF176B70)
val WorkLogPriorityLow = Color(0xFF63758A)
